/** Pilot month data — kept in sync with prototype mock for August 2026. */

export const PILOT_SERVICES = [
  { id: 's01', name: 'Sunday Service 1', date: '2026-08-02', day: 'Sunday', status: 'Scheduled' },
  { id: 's02', name: 'Sunday Service 2', date: '2026-08-02', day: 'Sunday', status: 'Scheduled' },
  { id: 's03', name: 'Tuesday Service', date: '2026-08-04', day: 'Tuesday', status: 'Scheduled' },
  { id: 's04', name: 'Friday Service', date: '2026-08-07', day: 'Friday', status: 'Scheduled' },
  { id: 's05', name: 'Sunday Service 1', date: '2026-08-09', day: 'Sunday', status: 'Scheduled' },
  { id: 's06', name: 'Sunday Service 2', date: '2026-08-09', day: 'Sunday', status: 'Scheduled' },
  { id: 's07', name: 'Tuesday Service', date: '2026-08-11', day: 'Tuesday', status: 'Scheduled' },
  { id: 's08', name: 'Friday Service', date: '2026-08-14', day: 'Friday', status: 'Scheduled' },
  { id: 's09', name: 'Sunday Service 1', date: '2026-08-16', day: 'Sunday', status: 'Scheduled' },
  { id: 's10', name: 'Sunday Service 2', date: '2026-08-16', day: 'Sunday', status: 'Scheduled' },
  { id: 's11', name: 'Tuesday Service', date: '2026-08-18', day: 'Tuesday', status: 'Scheduled' },
  { id: 's12', name: 'Friday Service', date: '2026-08-21', day: 'Friday', status: 'Scheduled' },
  { id: 's13', name: 'Sunday Service 1', date: '2026-08-23', day: 'Sunday', status: 'Scheduled' },
  { id: 's14', name: 'Sunday Service 2', date: '2026-08-23', day: 'Sunday', status: 'Scheduled' },
  { id: 's15', name: 'Tuesday Service', date: '2026-08-25', day: 'Tuesday', status: 'Scheduled' },
  { id: 's16', name: 'Friday Service', date: '2026-08-28', day: 'Friday', status: 'Scheduled' },
  { id: 's17', name: 'Igaburo Service', date: '2026-08-29', day: 'Saturday', status: 'Scheduled' },
  { id: 's18', name: 'Sunday Service 1', date: '2026-08-30', day: 'Sunday', status: 'Scheduled' },
  { id: 's19', name: 'Sunday Service 2', date: '2026-08-30', day: 'Sunday', status: 'Scheduled' },
]

export const PILOT_CHOIR_ASSIGNMENTS = [
  { service: 'Sunday Service 1', date: '02 Aug', choirs: 'Hope Choir, El Bethel Choir, Elim Choir', status: 'Assigned' },
  { service: 'Sunday Service 2', date: '02 Aug', choirs: "Ijwi ry'Umwami Yesu Choir, Integuza Choir, Yerusalemu Choir", status: 'Assigned' },
  { service: 'Sunday Service 1', date: '09 Aug', choirs: "Hope Choir, Ijwi ry'Umwami Yesu Choir, Integuza Choir", status: 'Assigned' },
  { service: 'Sunday Service 2', date: '09 Aug', choirs: 'El Bethel Choir, Elim Choir', status: 'Assigned' },
  { service: 'Sunday Service 1', date: '16 Aug', choirs: 'Hope Choir, El Bethel Choir, Integuza Choir', status: 'Assigned' },
  { service: 'Sunday Service 2', date: '16 Aug', choirs: "Ijwi ry'Umwami Yesu Choir, Elim Choir, Beulah Choir", status: 'Assigned' },
  { service: 'Sunday Service 1', date: '23 Aug', choirs: "Hope Choir, Elim Choir, Ijwi ry'Umwami Yesu Choir", status: 'Assigned' },
  { service: 'Sunday Service 2', date: '23 Aug', choirs: 'El Bethel Choir, Integuza Choir', status: 'Assigned' },
  { service: 'Sunday Service 1', date: '30 Aug', choirs: "Hope Choir, El Bethel Choir, Ijwi ry'Umwami Yesu Choir", status: 'Assigned' },
  { service: 'Sunday Service 2', date: '30 Aug', choirs: 'Elim Choir, Integuza Choir', status: 'Assigned' },
  { service: 'Tuesday Service', date: '04 Aug', choirs: 'El Bethel Choir', status: 'Assigned' },
  { service: 'Tuesday Service', date: '11 Aug', choirs: "Ijwi ry'Umwami Yesu Choir", status: 'Assigned' },
  { service: 'Tuesday Service', date: '18 Aug', choirs: 'Elim Choir', status: 'Assigned' },
  { service: 'Tuesday Service', date: '25 Aug', choirs: 'Integuza Choir', status: 'Assigned' },
  { service: 'Friday Service', date: '07 Aug', choirs: 'Integuza Choir', status: 'Assigned' },
  { service: 'Friday Service', date: '14 Aug', choirs: 'El Bethel Choir', status: 'Assigned' },
  { service: 'Friday Service', date: '21 Aug', choirs: "Ijwi ry'Umwami Yesu Choir", status: 'Assigned' },
  { service: 'Friday Service', date: '28 Aug', choirs: 'Elim Choir', status: 'Assigned' },
  { service: 'Igaburo Service', date: '29 Aug', choirs: 'El Bethel Choir, Integuza Choir', status: 'Assigned' },
]

export const ADMIN_ROSTER = [
  { id: '1', name: 'Samuel Niyonzima', role: 'President' },
  { id: '2', name: 'Emmanuel Habimana', role: 'Vice President' },
  { id: '3', name: 'Alice Mukamana', role: 'Secretary' },
  { id: '4', name: 'Jean Claude Uwimana', role: 'Treasurer' },
  { id: '5', name: 'David Mugisha', role: 'Coordinator' },
]

const CHOIR_ROTATION = [
  'El Bethel Choir',
  "Ijwi ry'Umwami Yesu Choir",
  'Elim Choir',
  'Integuza Choir',
  'Yerusalemu Choir',
  'Beulah Choir',
  null,
]

export const PROTOCOL_NAMES = [
  'Jean Bosco Ndayisaba',
  'Marie Claire Uwamahoro',
  'Théogène Hakizimana',
  'Vestine Mukamurenzi',
  'Consolee Uwizeye',
  'Alexis Mbarushimana',
  'Chantal Nyiraneza',
  'Innocent Bizimana',
  'Donatille Uwiringiyimana',
  'Valens Nkurikiyimana',
  'Beatha Nshimiyimana',
  'Moise Uwamariya',
  'Goretti Hategekimana',
  'Placide Ingabire',
  'Joselyne Gasana',
  'Fabrice Umutoni',
  'Liliane Niyonkuru',
  'Pascal Mukandori',
  'Immaculée Ndayambaje',
  'Olivier Uwimana',
  'Tharcisse Mugabo',
  'Gaudence Nkurunziza',
  'Speciose Mukandayisenga',
  'Annonciata Uwera',
  'Viateur Irakoze',
  'Deogratias Niyonsaba',
  'Fidèle Niyonsenga',
  'Liberata Uwimbabazi',
  'Athanase Kamanzi',
  'Gérard Murekatete',
  'Solange Nshuti',
  'Bernadette Habyarimana',
  'Odette Mukamana',
  'Cyprien Bizimana',
  'Callixte Nyirahabimana',
  'Félicien Munezero',
  'Angélique Mukarukundo',
  'Ildephonse Ntirenganya',
  'Josephine Ndayisenga',
  'Alphonse Niyigena',
  'Delphine Uwiragiye',
  'Boniface Nsengimana',
  'Jeannette Mukeshimana',
  'Edouard Niyitegeka',
  'Colette Habiyakare',
  'Augustin Nsabimana',
  'Scholastique Mukamuhizi',
  'Léonard Niyonzima',
  'Vénuste Nsengiyumva',
  'Pacifique Niyomugabo',
  'Clarisse Mukamurigo',
  'Faustin Niyonshuti',
  'Seraphine Mukamuhaye',
  'Théophile Niyonsaba',
  'Marie Grace Uwiringiyimana',
  'Jean Paul Nkurunziza',
  'Pierre Claver Mbarushimana',
  'Marie Thérèse Nyiraneza',
  'Elie Ndayambaje',
  'Esther Mukandori',
  'Samuel Niyonkuru',
  'Ruth Umutoni',
  'Daniel Gasana',
  'Sarah Ingabire',
  'James Irakoze',
  'Andrew Kamanzi',
  'Grace Murekatete',
  'Peter Nshuti',
  'Alice Nyirahabimana',
  'Joseph Niyigena',
  'Rose Uwiragiye',
  'Simon Nsengimana',
  'Joyce Mukeshimana',
  'Paul Ntaganda',
  'Vestine Nyiraminani',
]

function phoneForIndex(i) {
  return `+250 78${String(1000000 + i).slice(-7)}`
}

export function buildMemberRows() {
  const admin = ADMIN_ROSTER.map((a, i) => ({
    id: a.id,
    name: a.name,
    phone: phoneForIndex(i),
    role: a.role,
    status: 'Active',
    attendance_rate: null,
    choir: null,
  }))
  const protocol = PROTOCOL_NAMES.map((name, i) => ({
    id: String(6 + i),
    name,
    phone: phoneForIndex(10 + i),
    role: 'Member',
    status: 'Active',
    attendance_rate: 72 + (i * 5) % 27,
    choir: CHOIR_ROTATION[i % CHOIR_ROTATION.length],
  }))
  return [...admin, ...protocol]
}

export function protocolNamePool(members) {
  return members.filter((m) => m.role === 'Member' && m.status === 'Active').map((m) => m.name)
}
